// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod/v3';

export const zFoo = z.object({
    foo: z.array(z.union([z.string().min(1).max(10).regex(/^[a-z]+$/), z.string()])).optional()
});
