// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

export const zFoo = z.object({
    foo: z.optional(z.array(z.union([z.string().check(z.minLength(1), z.maxLength(10), z.regex(/^[a-z]+$/)), z.string()])))
});
